/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class LoadUI extends Laya.View {
		public progress_JD:Laya.ProgressBar;
		public label_Tips:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Load");
        }
    }
    REG("ui.LoadUI",LoadUI);
    export class StartUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Start");
        }
    }
    REG("ui.StartUI",StartUI);
}